language: objective-c
osx_image: xcode7.1
before_install:
  - gem install xcpretty
script:
  - xcodebuild -version
  - xcodebuild -project Example/FlowingMenuExample.xcodeproj -scheme FlowingMenuTests -sdk iphonesimulator -destination "OS=9.1,name=iPad 2" -configuration Release ONLY_ACTIVE_ARCH=YES test | xcpretty -c
  - xcodebuild -project Example/FlowingMenuExample.xcodeproj -scheme FlowingMenuUITests -sdk iphonesimulator -destination "OS=9.1,name=iPad 2" -configuration Release ONLY_ACTIVE_ARCH=YES test | xcpretty -c
after_success:
  - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/2b2272f20f664219407989de9d1c550ddf7d48b5/codecov)
